---
# tasks file for mgmt

- name: "Add Repo - Multiverse"
  command: add-apt-repository multiverse warn=no

- name: "Update all packages"
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Reboot target host
  ansible.builtin.reboot:
    reboot_timeout: 180
